resource:
  properties:
    type:
      example: TransactionReceipt

attributes:
  allOf:
  - $ref: '#/transactionReceipt/transactionHash'
  - $ref: '#/transactionReceipt/transactionIndex'
  - $ref: '#/transactionReceipt/blockHash'
  - $ref: '#/transactionReceipt/blockNumber'
  - $ref: '#/transactionReceipt/contractAddress'
  - $ref: '#/transactionReceipt/cumulativeGasUsed'
  - $ref: '#/transactionReceipt/fromAddress'
  - $ref: '#/transactionReceipt/toAddress'
  - $ref: '#/transactionReceipt/gasUsed'
  - $ref: '#/transactionReceipt/logs'
  - $ref: '#/transactionReceipt/logsBloom'
  - $ref: '#/transactionReceipt/status'

getResource:
  title: Transaction Receipt
  description: Transaction Receipt details associated with the resource
  type: object
  allOf:
  - $ref: '#/ethereum/resourceId'
  - $ref: '#/resource'
  - properties:
      attributes:
        $ref: '#/attributes'

ethereum:
  $ref: ../ethereum/dataTypes.yaml

transactionReceipt:
  $ref: dataTypes.yaml
