resource:
  properties:
    type:
      example: PermissionLink
      description: PermissionLink

attributes:
  allOf:
    - $ref: '#/permissionLinks/name'
    - $ref: '#/permissionLinks/expirationDate'
    - $ref: '#/permissionLinks/shipmentId'
    - $ref: '#/dataTypes/createdAt'

relationships:
  type: object
  description: Shipment Relation for this resource
  properties:
    shipment:
      type: object
      description: Shipment associated with this permission link
      properties:
        data:
          allOf:
            - $ref: '#/shipments/resource'
            - $ref: '#/dataTypes/resourceId'

createAttributes:
  allOf:
    - $ref: '#/permissionLinks/name'
    - $ref: '#/permissionLinks/expirationDate'

getResource:
  allOf:
    - $ref: '#/resource'
    - properties:
        attributes:
          $ref: '#/attributes'
        relationships:
          $ref: '#/relationships'

getResponse:
  allOf:
    - $ref: '#/jsonApi/data'
    - properties:
        data:
          $ref: '#/getResource'

listResponse:
  allOf:
    - $ref: '#/jsonApi/dataArray'
    - $ref: '#/jsonApi/linksAndMeta'
    - properties:
        data:
          items:
            $ref: '#/getResource'

createRequest:
  allOf:
    - $ref: '../jsonApi/requestBody.yaml#/createData'
    - properties:
        data:
          $ref: '#/createResource'

createResource:
  allOf:
    - $ref: '#/resource'
    - properties:
        attributes:
          $ref: '#/createAttributes'

permissionLinks:
  $ref: dataTypes.yaml

shipments:
  $ref: ../shipments/schema.yaml

dataTypes:
  $ref: ../core/dataTypes.yaml

jsonApi:
  $ref: ../jsonApi/schema.yaml
