resource:
  properties:
    type:
      example: CsvDocument

attributes:
  allOf:
    - $ref: '#/document/name'
    - $ref: '#/document/description'
    - $ref: '#/document/fileType'
    - $ref: '#/document/uploadStatus'
    - $ref: '#/document/processingStatus'
    - $ref: '#/dataTypes/createdAt'
    - $ref: '#/dataTypes/updatedAt'

getResource:
  allOf:
    - $ref: '#/resource'
    - properties:
        attributes:
          $ref: '#/attributes'

getResponse:
  allOf:
    - $ref: '#/jsonApi/data'
    - properties:
        data:
          $ref: '#/getResource'

createResponse:
  allOf:
    - $ref: '../jsonApi/schema.yaml#/data'
    - properties:
        data:
          $ref: '#/getResource'
    - properties:
        data:
          properties:
            meta:
              $ref: './dataTypes.yaml#/presignedS3Post'

listResponse:
  allOf:
    - $ref: '#/jsonApi/dataArray'
    - $ref: '#/jsonApi/linksAndMeta'
    - properties:
        data:
          items:
            $ref: '#/getResource'

document:
  $ref: './dataTypes.yaml'

dataTypes:
  $ref: '../core/dataTypes.yaml'

jsonApi:
  $ref: '../jsonApi/schema.yaml'
