dataTypes:
  $ref: ../core/dataTypes.yaml

active:
  name: active
  in: query
  description: Device's location reporting status at the moment of the request
  required: false
  schema:
    type: boolean
    enum: [true, false]
    example: true

inBbox:
  name: in_bbox
  in: query
  description: Device's location viewport box coordinates, in the form `minLon, minLat, maxLon, maxLat`
  required: false
  schema:
    type: string
    example: -82.5,34.5,-83,36

state:
  name: state
  in: query
  description: Returns the devices for which the attached shipments are in the provided transit state.
  schema:
    type: string
    enum: [IN_TRANSIT, AWAITING_DELIVERY, DELIVERED]
    example: IN_TRANSIT

path:
  required: true
  name: device_id
  in: path
  description: ID of the device
  schema:
    $ref: '#/dataTypes/uuid'
