resource:
    properties:
      type:
        description: AsyncJob
        example: AsyncJob

attributes:
  allOf:
  - $ref: '#/job/state'
  - $ref: '#/parameters'
  - $ref: '#/dataTypes/createdAt'
  - $ref: '#/dataTypes/updatedAt'
  - $ref: '#/job/lastTry'
  - $ref: '#/job/delay'

message:
  type: object
  properties:
    - $ref: '#/job/state'
    - $ref: '#/parameters'

meta:
  type: object
  properties:
    count:
      type: integer
      example: 1
      description: Size of the data array


relationships:
  type: object
  description: Related objects for this resource
  properties:
    actions:
      type: object
      properties:
        data:
          items:
            type: object
            $ref: '#/ethAction/actions'
        meta:
          $ref: '#/meta'

    message_set:
      type: object
      properties:
        data:
          type: array
          items:
            type: object
            $ref: '#/messageRef/messageSet'
        meta:
          $ref: '#/meta'

    shipment:
      type: object
      description: Shipment associated with this document
      properties:
        data:
          allOf:
            - $ref: '#/shipments/resource'
            - $ref: '#/dataTypes/resourceId'

parameters:
  type: object
  properties:
    parameters:
      type: object
      properties:
        rpcClass:
          $ref: '#/job/rpcClass/properties/rpcClass'
        rpc_method:
          $ref: '#/job/rpcMethod/properties/rpc_method'
        rpcParameters:
          $ref: '#/rpcParameters/properties/rpcParameters'
        signing_wallet_id:
          $ref: '#/job/signingWalletId/properties/signing_wallet_id'

rpcParameters:
  type: object
  properties:
    rpcParameters:
      type: array
      items:
        anyOf:
        - type: string
        - type: number

getResource:
  allOf:
  - $ref: '#/resource'
  - properties:
      attributes:
        $ref: '#/attributes'
      relationships:
        $ref: '#/relationships'

includedResource:
  title: Async Job
  description: Async Job associated with the resource
  type: object
  allOf:
    - $ref: '#/dataTypes/resourceId'
    - $ref: '#/getResource'

getResponse:
  allOf:
  - $ref: '#/jsonApi/data'
  - properties:
      data:
        $ref: '#/getResource'

listResponse:
  allOf:
  - $ref: '#/jsonApi/dataArray'
  - $ref: '#/jsonApi/linksAndMeta'
  - properties:
      data:
        items:
          $ref: '#/getResource'
      included:
        items:
          type: object
          $ref: '#/messageRef/includedResource'

ethAction:
  $ref: ../ethAction/schema.yaml

shipments:
  $ref: ../shipments/schema.yaml

job:
  $ref: dataTypes.yaml

dataTypes:
  $ref: ../core/dataTypes.yaml

messageRef:
  $ref: ../messages/schema.yaml

jsonApi:
  $ref: ../jsonApi/schema.yaml
