path:
  required: true
  name: shipment_id
  in: path
  description: ID of the Shipment
  schema:
    $ref: '#/dataTypes/uuid'

asPoint:
  name: as_point
  in: query
  description: Returns tracking data as points
  schema:
    type: string

asLine:
  name: as_line
  in: query
  description: Returns tracking data as line
  schema:
    type: string

has_ship_from_location:
  name: has_ship_from_location
  in: query
  description: Returns shipments with associated ship_from_location objects.
  schema:
    type: boolean

has_ship_to_location:
  name: has_ship_to_location
  in: query
  description: Returns shipments with associated ship_to_location objects.
  schema:
    type: boolean

has_final_destination_location:
  name: has_final_destination_location
  in: query
  description: Returns shipments with associated final_destination_location objects.
  schema:
    type: string

ship_to_location__city:
  name: ship_to_location__city
  in: query
  description: Returns shipments with associated ship_to_location city.
  schema:
    type: boolean

ship_to_location__state:
  name: ship_to_location__state
  in: query
  description: Returns shipments with associated ship_to_location state.
  schema:
    type: string

ship_to_location__postal_code:
  name: ship_to_location__postal_code
  in: query
  description: Returns shipments with associated ship_to_location postal code.
  schema:
    type: string

ship_to_location__country:
  name: ship_to_location__state
  in: query
  description: Returns shipments with associated ship_to_location state.
  schema:
    type: string

ship_from_location__city:
  name: ship_from_location__city
  in: query
  description: Returns shipments with associated ship_from_location city.
  schema:
    type: string

ship_from_location__state:
  name: ship_from_location__state
  in: query
  description: Returns shipments with associated ship_from_location state.
  schema:
    type: string

ship_from_location__postal_code:
  name: ship_from_location__postal_code
  in: query
  description: Returns shipments with associated ship_from_location postal code.
  schema:
    type: string

ship_from_location__country:
  name: ship_from_location__state
  in: query
  description: Returns shipments with associated ship_from_location state.
  schema:
    type: string

final_destination_location__city:
  name: final_destination_location__city
  in: query
  description: Returns shipments with associated final_destination_location city.
  schema:
    type: string

final_destination_location__state:
  name: final_destination_location__state
  in: query
  description: Returns shipments with associated final_destination_location state.
  schema:
    type: string

final_destination_location__postal_code:
  name: final_destination_location__postal_code
  in: query
  description: Returns shipments with associated final_destination_location postal code.
  schema:
    type: string

final_destination_location__country:
  name: final_destination_location__state
  in: query
  description: Returns shipments with associated final_destination_location state.
  schema:
    type: string

state:
  name: state
  in: query
  description: Returns shipments with the provided transit state.
  schema:
    type: string
    enum: [AWAITING_PICKUP, IN_TRANSIT, AWAITING_DELIVERY, DELIVERED]

exception:
  name: exception
  in: query
  description: Returns shipments with the provided exception state.
  schema:
    type: string
    enum: [NONE, CUSTOMS_HOLD, DOCUMENTATION_ERROR]

delayed:
  name: delayed
  in: query
  description: Returns shipments that are delayed, based on boolean value.
  schema:
    type: boolean

permissionLinkId:
  name: permission_link
  in: query
  description: When included and valid, a permission link parameter provides unauthenticated read-only access to a shipment.
  schema:
    $ref: '#/dataTypes/uuid'

dataTypes:
  $ref: ../core/dataTypes.yaml
