resource:
  properties:
    type:
      example: Location

geometry:
  properties:
    geometry:
      type: object
      name: geometry
      allOf:
      - $ref: '#/location/type'
      - $ref: '#/location/coordinates'

attributes:
  allOf:
  - $ref: '#/location/name'
  - $ref: '#/location/address_1'
  - $ref: '#/location/address_2'
  - $ref: '#/location/city'
  - $ref: '#/location/state'
  - $ref: '#/location/country'
  - $ref: '#/location/postalCode'
  - $ref: '#/location/phoneNumber'
  - $ref: '#/location/faxNumber'
  - $ref: '#/dataTypes/createdAt'
  - $ref: '#/dataTypes/updatedAt'
  - $ref: '#/geometry'

includedResource:
  allOf:
  - $ref: '#/dataTypes/resourceId'
  - $ref: '#/getResource'

getResource:
  allOf:
  - $ref: '#/resource'
  - properties:
      attributes:
        $ref: '#/attributes'

permissionLinks:
  $ref: ../permissionLinks/dataTypes.yaml

dataTypes:
  $ref: ../core/dataTypes.yaml

location:
  $ref: dataTypes.yaml

jsonApi:
  $ref: ../jsonApi/schema.yaml
