version: '3.4'
services:

  minio:
    image: minio/minio
    expose:
      - '9000'
    networks:
      - portal
    environment:
    - MINIO_ACCESS_KEY=TEST-DEV-KEY
    - MINIO_SECRET_KEY=NON-TRIVIAL-SECRETKEY
    - MINIO_DOMAIN=minio
    command: server /data --address minio:9000

  redis_db:
    image: circleci/redis
    expose:
      - '6379'
    networks:
      - portal
    volumes:
      - /data/shipchain/transmission/redis:/data
    command: >
      --requirepass redis_pass

  psql:
    image: circleci/postgres:9.6-alpine-postgis
    expose:
      - '5432'
    networks:
      - portal
    environment:
      - POSTGRES_USER=transmission
      - POSTGRES_PASS=transmission
      - POSTGRES_HOST=psql
      - POSTGRES_DBNAME=transmission
      - ALLOW_IP_RANGE=0.0.0.0/0

  runserver:
    build:
      context: ../
      target: test
    image: transmission-django-test
    command: sh -c 'while sleep 3600; do :; done'
    ports:
      - "8000:8000"
    networks:
      - portal
    links:
      - psql
      - redis_db
      - minio
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - ENV
      - SECRET_KEY
      - SERVICE=circleci
      - REDIS_URL=redis://:redis_pass@redis_db:6379/1
      - AWS_ACCESS_KEY_ID=TEST-DEV-KEY
      - AWS_SECRET_ACCESS_KEY=NON-TRIVIAL-SECRETKEY

networks:
  portal:
    driver: bridge
