version: '2.1'
services:

  redis_db:
    image: circleci/redis
    expose:
      - '6379'
    networks:
      - portal
    volumes:
      - /data/shipchain/transmission/redis:/data
    command: >
      --requirepass redis_pass

  psql:
    image: circleci/postgres:9.6-alpine-postgis
    expose:
      - '5432'
    networks:
      - portal
    environment:
      POSTGRES_USER: transmission
      POSTGRES_PASSWORD: transmission
      POSTGRES_DB: transmission

  runserver:
    extends:
      service: transmission-django
      file: build.yml
    command: sleep infinity
    ports:
      - "8000:8000"
    networks:
      - portal
    links:
      - psql
      - redis_db
    environment:
      - ENV
      - SECRET_KEY
      - SERVICE=circleci
      - REDIS_URL=redis://:redis_pass@redis_db:6379/1

networks:
  portal:
    driver: bridge
