version: '2.1'
services:

  minio:
    image: minio/minio
    ports:
    - "9090:9000"
    expose:
      - '9000'
    volumes:
    - /data/shipchain/transmission/minio/data:/data
    - /data/shipchain/transmission/minio/config:/root/.minio
    environment:
    - MINIO_ACCESS_KEY=TEST-DEV-KEY
    - MINIO_SECRET_KEY=NON-TRIVIAL-SECRETKEY
    - MINIO_DOMAIN=minio
    command: server /data --address minio:9000

  redis_db:
    image: redis
    expose:
      - '6379'
    volumes:
      - /data/shipchain/transmission/redis:/data
    command: >
      --requirepass redis_pass --appendonly yes

  psql:
    image: mdillon/postgis:9.6
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: transmission
      POSTGRES_PASSWORD: transmission
      POSTGRES_DB: transmission
    volumes:
      - /data/shipchain/transmission/postgresql:/var/lib/postgresql

  django_shell: # This is a one-shot command runner service, for manage.py or bash, it dies immediately
    extends:
      service: transmission-django-dev
      file: build.yml
    volumes:
      - ../:/app
    links:
      - psql
      - redis_db
      - minio
    environment:
      - ENV
      - SECRET_KEY
      - SERVICE=django_shell
      - REDIS_URL
      - ENGINE_RPC_URL=http://engine-rpc:2000
      - INTERNAL_URL=http://transmission-runserver:8000
      - PROFILES_URL #http://profiles-runserver:8000
      - ELASTICSEARCH_URL
    command: "bash"
    entrypoint: []

  runserver:
    extends:
      service: transmission-django-dev
      file: build.yml
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    networks:
      default:
        aliases:
          - transmission-runserver
      portal:
        aliases:
          - transmission-runserver
    links:
      - psql
      - redis_db
      - minio
    volumes:
      - ../:/app
      - ./django/pip.cache:/build/pip.volume
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - ENV
      - SECRET_KEY
      - SERVICE=runserver
      - REDIS_URL
      - ENGINE_RPC_URL=http://engine-rpc:2000
      - INTERNAL_URL=http://transmission-runserver:8000
      - PROFILES_URL #http://profiles-runserver:8000
      - ELASTICSEARCH_URL

  celery:
    extends:
      service: transmission-django-dev
      file: build.yml
    command: ["watchmedo", "auto-restart", "-d", ".", "-p", "'*.py'", "--", "celery", "worker", "-A", "apps"]
    networks:
      default:
        aliases:
          - transmission-celery
      portal:
        aliases:
          - transmission-celery
    links:
      - psql
      - redis_db
      - minio
    volumes:
      - ../:/app
    environment:
      - ENV
      - SECRET_KEY
      - SERVICE=celery
      - REDIS_URL
      - ENGINE_RPC_URL=http://engine-rpc:2000
      - INTERNAL_URL=http://transmission-runserver:8000
      - PROFILES_URL #http://profiles-runserver:8000
      - ELASTICSEARCH_URL
    entrypoint: []

networks:
  portal:
    external: true
