path:
  required: true
  name: transaction_hash
  in: path
  description: Hash of a signed Ethereum transaction
  schema:
    $ref: '#/ethereum/transactionHash'

wallet_id:
  required: true
  name: wallet_id
  in: query
  description: Wallet ID to filter transactions by
  schema:
    $ref: '#/dataTypes/uuid'

wallet_address:
  required: true
  name: wallet_address
  in: query
  description: Wallet Address to filter transactions by
  schema:
    $ref: '#/ethereum/address'

include_async_job_action:
  required: false
  name: include
  in: query
  description: Include AsyncActions for AsyncJobs
  schema:
    type: string
    enum:
      - async_job.actions

permissionLinkId:
  name: permission_link
  in: query
  description: When included and valid, a permission link parameter provides unauthenticated read-only access to the shipment's transactions.
  schema:
    $ref: '#/dataTypes/uuid'

dataTypes:
  $ref: ../core/dataTypes.yaml

ethereum:
  $ref: ../ethereum/dataTypes.yaml
