resource:
  properties:
    type:
      example: Transaction

attributes:
  allOf:
   - $ref: '#/transaction/hash'
   - $ref: '#/transaction/nonce'
   - $ref: '#/transaction/chainId'
   - $ref: '#/transaction/toAddress'
   - $ref: '#/transaction/value'
   - $ref: '#/transaction/gasLimit'
   - $ref: '#/transaction/gasPrice'
   - $ref: '#/transaction/data'

getResource:
  allOf:
  - $ref: '#/resource'
  - properties:
      attributes:
        $ref: '#/attributes'

includedResource:
  title: Transaction
  description: Transaction details associated with the resource
  type: object
  allOf:
    - $ref: '#/ethereum/resourceId'
    - $ref: '#/getResource'

ethereum:
  $ref: ../ethereum/dataTypes.yaml

transaction:
  $ref: dataTypes.yaml
