resource:
    properties:
      type:
        example: EthAction

attributes:
  allOf:
  - $ref: '#/ethereum/transactionHash'
  - $ref: '#/dataTypes/createdAt'
  - $ref: '#/dataTypes/updatedAt'

relationships:
  type: array
  items:
  - allOf:
    - $ref: '#/ethereum/resourceId'
    - $ref: '#/transactionSchema/resource'
  - allOf:
    - $ref: '#/ethereum/resourceId'
    - $ref: '#/transactionReceipt/resource'
  - allOf:
    - $ref: '#/dataTypes/resourceId'
    - $ref: '#/job/resource'

included:
  type: array
  items:
  - $ref: '#/job/getResource'
  - $ref: '#/transactionSchema/getResource'
  - $ref: '#/transactionReceipt/getResource'

getResource:
  allOf:
  - $ref: '#/ethereum/resourceId'
  - $ref: '#/resource'
  - properties:
      attributes:
        $ref: '#/attributes'
      relationships:
        $ref: '#/relationships'

getResponse:
  allOf:
  - $ref: '#/jsonApi/data'
  - properties:
      data:
        $ref: '#/getResource'
      included:
        $ref: '#/included'

listResponse:
  allOf:
  - $ref: '#/jsonApi/dataArray'
  - $ref: '#/jsonApi/linksAndMeta'
  - properties:
      data:
        items:
          $ref: '#/getResource'
      included:
        items:
          $ref: '#/included'

dataTypes:
  $ref: ../core/dataTypes.yaml

ethereum:
  $ref: ../ethereum/dataTypes.yaml

transaction:
  $ref: ../transactions/dataTypes.yaml

transactionSchema:
  $ref: ../transactions/schema.yaml

job:
  $ref: ../jobs/schema.yaml

jsonApi:
  $ref: ../jsonApi/schema.yaml

transactionReceipt:
  $ref: ../transactionReceipts/schema.yaml
