resource:
    properties:
      type:
        example: LoadShipment

attributes:
  allOf:
  - $ref: '#/loadShipment/shipmentStatus'
  - $ref: '#/loadShipment/escrowStatus'
  - $ref: '#/loadShipment/fundingType'
  - $ref: '#/loadShipment/shipmentId'
  - $ref: '#/loadShipment/shipmentAmount'
  - $ref: '#/loadShipment/paidAmount'
  - $ref: '#/loadShipment/paidTokens'
  - $ref: '#/shipment/shipperWalletId'
  - $ref: '#/shipment/carrierWalletId'
  - $ref: '#/ethereum/moderator'
  - $ref: '#/loadShipment/contractFunded'
  - $ref: '#/loadShipment/shipmentCreated'
  - $ref: '#/loadShipment/validUntil'
  - $ref: '#/loadShipment/startBlock'
  - $ref: '#/loadShipment/endBlock'
  - $ref: '#/loadShipment/escrowFunded'
  - $ref: '#/loadShipment/shipmentCommittedByCarrier'
  - $ref: '#/loadShipment/commitmentConfirmedDate'
  - $ref: '#/loadShipment/shipmentCompletedByCarrier'
  - $ref: '#/loadShipment/shipmentAcceptedByShipper'
  - $ref: '#/loadShipment/shipmentCanceledByShipper'
  - $ref: '#/loadShipment/escrowPaid'
  - $ref: '#/dataTypes/createdAt'
  - $ref: '#/dataTypes/updatedAt'

getResource:
  allOf:
  - $ref: '#/resource'
  - properties:
      attributes:
        $ref: '#/attributes'

getResponse:
  allOf:
  - $ref: '#/jsonApi/data'
  - properties:
      data:
        $ref: '#/getResource'

ethereum:
  $ref: ../ethereum/dataTypes.yaml

loadShipment:
  $ref: dataTypes.yaml

shipment:
  $ref: ../shipments/dataTypes.yaml

dataTypes:
  $ref: ../core/dataTypes.yaml

jsonApi:
  $ref: ../jsonApi/schema.yaml
