resource:
    properties:
      type:
        description: LoadShipment
        example: LoadShipment

attributes:
  type: object
  description: LoadShipment Attributes
  allOf:
  - $ref: '#/loadShipment/shipmentState'
  - $ref: '#/loadShipment/escrowState'
  - $ref: '#/loadShipment/fundingType'
  - $ref: '#/loadShipment/contractedAmount'
  - $ref: '#/loadShipment/fundedAmount'
  - $ref: '#/loadShipment/createdAt'
  - $ref: '#/loadShipment/shipper'
  - $ref: '#/loadShipment/carrier'
  - $ref: '#/loadShipment/moderator'
  - $ref: '#/loadShipment/refundAddress'
  - $ref: '#/loadShipment/vaultHash'
  - $ref: '#/loadShipment/vaultUri'

relationships:
  type: object
  description: Shipment Relation for this resource
  properties:
    shipment:
      type: object
      description: Shipment associated with this Load Shipment
      properties:
        data:
          allOf:
            - $ref: '../shipments/schema.yaml#/resource'
            - $ref: '../core/dataTypes.yaml#/resourcePk'

includedResource:
  title: Load Shipment
  description: Load Shipment associated with the resource
  type: object
  allOf:
  - $ref: '#/dataTypes/resourceId'
  - $ref: '#/getResource'

getResource:
  allOf:
  - $ref: '#/resource'
  - properties:
      attributes:
        $ref: '#/attributes'
      relationships:
        $ref: '#/relationships'

getResponse:
  allOf:
  - $ref: '#/jsonApi/data'
  - properties:
      data:
        $ref: '#/getResource'

ethereum:
  $ref: ../ethereum/dataTypes.yaml

loadShipment:
  $ref: dataTypes.yaml

shipment:
  $ref: ../shipments/dataTypes.yaml

dataTypes:
  $ref: ../core/dataTypes.yaml

jsonApi:
  $ref: ../jsonApi/schema.yaml
