resource:
  properties:
    type:
      description: Document
      example: Document

attributes:
  allOf:
    - $ref: '#/document/name'
    - $ref: '#/document/description'
    - $ref: '#/document/documentType'
    - $ref: '#/document/ownerId'
    - $ref: '#/document/fileType'
    - $ref: '#/document/uploadStatus'
    - $ref: '#/dataTypes/createdAt'
    - $ref: '#/dataTypes/updatedAt'

relationships:
  type: object
  description: Shipment Relation for this resource
  properties:
    shipment:
      type: object
      description: Shipment associated with this document
      properties:
        data:
          allOf:
            - $ref: '#/shipments/resource'
            - $ref: '#/dataTypes/resourceId'

getResource:
  allOf:
    - $ref: '#/resource'
    - properties:
        attributes:
          $ref: '#/attributes'
        relationships:
          $ref: '#/relationships'

getResponse:
  allOf:
    - $ref: '#/jsonApi/data'
    - properties:
        data:
          $ref: '#/getResource'
    - properties:
        data:
          properties:
            meta:
              oneOf:
                - $ref: '#/document/presignedS3Post'
                - $ref: '#/document/presignedS3Get'

createResponse:
  allOf:
    - $ref: '#/jsonApi/data'
    - properties:
        data:
          $ref: '#/getResource'
    - properties:
        data:
          properties:
            meta:
              $ref: '#/document/presignedS3Post'

listResponse:
  allOf:
    - $ref: '#/jsonApi/dataArray'
    - $ref: '#/jsonApi/linksAndMeta'
    - properties:
        data:
          items:
            $ref: '#/getResource'
    - properties:
        data:
          items:
            properties:
              meta:
                oneOf:
                - $ref: '#/document/presignedS3Post'
                - $ref: '#/document/presignedS3Get'

document:
  $ref: dataTypes.yaml

shipments:
  $ref: ../shipments/schema.yaml

dataTypes:
  $ref: ../core/dataTypes.yaml

jsonApi:
  $ref: ../jsonApi/schema.yaml
