page:
  name: page
  in: query
  description: Page number used for pagination
  required: false
  schema:
    type: integer
    format: int32
    example: 9

page_size:
  name: page_size
  in: query
  description: Number of objects displayed per page
  required: false
  schema:
    type: integer
    format: int32
    example: 9

search:
  name: search
  in: query
  description: Shipment info to search for.
  required: false
  schema:
    type: string
    format: format
    example: Shipment Name

ordering:
  name: ordering
  in: query
  description: Ordering of the objects. Default is descending order, add a `-` symbol before the variable to make it ascending.
  required: false
  schema:
    type: string
    enum: [created_at, updated_at, -created_at, -updated_at]
    example: -updated_at

permissionLinks:
  path:
    required: true
    name: permission_links_id
    in: path
    description: ID of the PermissionLink
    schema:
      $ref: '#/dataTypes/uuid'

location:
  path:
    required: true
    name: location_id
    in: path
    description: ID of the Location
    schema:
      $ref: '#/dataTypes/uuid'

job:
  path:
    required: true
    name: asyncjob_id
    in: path
    description: ID of the AsyncJob
    schema:
      $ref: '#/dataTypes/uuid'

dataTypes:
  $ref: dataTypes.yaml
